from typing import Optional


class Button:
    def is_key(self) -> bool: ...
    def is_controller(self) -> bool: ...
    def is_hat(self) -> bool: ...
    def is_mouse(self) -> bool: ...
    def value(self) -> Optional[int]: ...
