from typing import Callable, List
from .window.events import Viewport
from .graphics import Context

class GlGraphics:
    def clear_color(self, color: List[float]): ...
    def clear_stencil(self, value: int): ...
    def draw_begin(self, viewport: Viewport) -> Context: ...
    def draw_end(self): ...

def draw(gl: GlGraphics, viewport: Viewport, func: Callable[[Context, "GlGraphics"], None]): ...