from typing import Optional, Tuple


class Event:
    def is_input(self) -> bool: ...
    def is_loop(self) -> bool: ...

    def render_args(self) -> Optional[RenderArgs]: ...
    def update_args(self) -> Optional[UpdateArgs]: ...


class RenderArgs:
    @property
    def ext_dt(self) -> float: ...
    @property
    def window_size(self) -> Tuple[float, float]: ...
    @property
    def draw_size(self) -> Tuple[float, float]: ...
    @property
    def viewport(self) -> Viewport: ...

class UpdateArgs:
    @property
    def dt(self) -> float: ...

class Viewport:
    @property
    def rect(self) -> Tuple[int, int]: ...
    @property
    def draw_size(self) -> Tuple[int, int]: ...
    @property
    def window_size(self) -> Tuple[float, float]: ...