from ..piston2d.window.events import Viewport
from typing import Optional, Tuple


class Context:
    @property
    def viewport(self) -> Optional[Viewport]: ...
    def reset(self): ...
    def store_view(self): ...
    @property
    def view_size(self) -> Tuple[float, float]: ...