from typing import Callable, Tuple

__version__: str

class Pyston2dApp:
    def tick(self): ...

    def render(self, callable: Callable): ...
    def update(self, callable: Callable): ...

    def get_title(self) -> str: ...
    def set_title(self, title: str): ...


def init(title: str, size: Tuple[int, int]) -> Pyston2dApp: ...
