from typing import Tuple


class Window:
    def __init__(self, settings: WindowSettings) -> None: ...

class WindowSettings:
    def __init__(self, title: str, size: Tuple[int, int]) -> None: ...

    def get_title(self) -> str: ...
    def set_title(self, title: str): ...

    def get_size(self) -> Tuple[int, int]: ...
    def set_size(self, value: Tuple[int, int]): ...