name: Build document

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.platform.rust-target }}
        profile: minimal
        default: true
    
    - name: Install requirements
      run:  |
        python -m pip install -U -r requirements.txt
        python -m pip install -U -r requirements-doc.txt
    
    - name: Build
      run: python setup.py build
    
    - name: Build
      run: |
        sphinx-apidoc -o source piston2d
        make html
    
    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html