name: Build document

on:
  push:
    branches:
      - main

jobs:
  build_rust:
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    name: Rust build check 🛠
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.rust-target }}
          profile: minimal
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
  build_docs:
    if: "!contains(github.event.head_commit.message, '[skip docs]')"
    name: Build documentation 📚
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.platform.rust-target }}
        profile: minimal
        default: true
    
    - name: Install requirements
      run:  |
        python -m pip install -U -r requirements.txt
        python -m pip install -U -r requirements-doc.txt
    
    - name: Build to local pip
      run: python setup.py install
    
    - name: Build
      run: |
        sphinx-apidoc -o docs piston2d
        cd docs
        make html
    
    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
